import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base = process.env.VIEWER_URL || 'http://127.0.0.1:4173/';
fs.mkdirSync('test-results', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const failures = [], result = {};
const distance = (a,b) => Math.hypot(...a.map((v,i) => v-b[i]));
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, deviceScaleFactor: 1 });
  page.on('pageerror', error => failures.push(error.message));
  page.on('response', response => { if (response.url().startsWith(base) && response.status() >= 400) failures.push(`${response.status()} ${response.url()}`); });
  await page.goto(base, { waitUntil: 'domcontentloaded' });
  await page.waitForFunction(() => window.qingmingViewer?.snapshot().ready, { timeout: 120000 });
  const snap = () => page.evaluate(() => window.qingmingViewer.snapshot());
  await page.getByRole('button', { name: '暫停動畫', exact: true }).click();
  let state = await snap();
  assert.equal(state.skins, 99); assert.equal(state.clips, 1); assert.equal(state.duration, 30);
  assert.deepEqual(state.visitors.map(v=>v.asset).sort(), ['coral','pink','purple']);
  assert.ok(state.visitors.every(v=>v.bones===15 && v.head?.length===4 && v.hand?.length===4));
  const youngest = state.visitors.find(v=>v.asset==='coral');
  assert.equal(youngest.bodyScale,.66);
  assert.ok(state.visitors.filter(v=>v.asset!=='coral').every(v=>youngest.height < v.height*.80));
  const pausedTime = state.time;
  await page.waitForTimeout(350);
  assert.equal((await snap()).time, pausedTime);
  await page.getByRole('button', { name: '播放動畫', exact: true }).click();
  await page.waitForTimeout(550);
  assert.ok((await snap()).time > pausedTime + .05);
  await page.getByRole('button', { name: '暫停動畫', exact: true }).click();
  const beforeSeek = await snap();
  await page.locator('#scrubber').evaluate(el => { el.value='12.5'; el.dispatchEvent(new Event('input', { bubbles:true })); });
  const afterSeek = await snap();
  assert.equal(afterSeek.time, 12.5); assert.notDeepEqual(afterSeek.sampleBone, beforeSeek.sampleBone);
  for (const visitor of afterSeek.visitors) {
    const before = beforeSeek.visitors.find(v=>v.asset===visitor.asset);
    assert.notDeepEqual(visitor.head, before.head);
    assert.notDeepEqual(visitor.hand, before.hand);
  }
  await page.getByRole('button', { name: '放大', exact: true }).click();
  state = await snap();
  assert.ok(distance(state.camera,state.target) < distance(afterSeek.camera,afterSeek.target)*.9);
  await page.mouse.move(820,430); await page.mouse.down(); await page.mouse.move(1010,490,{steps:15}); await page.mouse.up();
  await page.waitForTimeout(200);
  assert.ok(distance((await snap()).camera,state.camera)>2);
  state = await snap();
  await page.mouse.move(820,430); await page.mouse.down({button:'right'}); await page.mouse.move(890,430,{steps:10}); await page.mouse.up({button:'right'});
  await page.waitForTimeout(200);
  assert.ok(distance((await snap()).target,state.target)>.2);
  await page.getByRole('button', { name: '橋上市集', exact:true }).click(); await page.waitForTimeout(1100);
  assert.equal(await page.getByRole('button', { name:'橋上市集',exact:true }).getAttribute('aria-pressed'),'true');
  await page.screenshot({path:'test-results/bridge.png'});
  await page.getByRole('button',{name:'回到初始視角'}).click(); await page.waitForTimeout(1100);
  state=await snap();assert.ok(distance(state.camera,[-43,54,62])<.2);
  await page.screenshot({path:'test-results/desktop.png'});
  const glb = await page.request.get(new URL('models/qingming.glb',base).href);
  assert.equal(glb.status(),200);assert.ok((await glb.body()).length<10*1024*1024);
  assert.equal((await page.request.head(new URL('tour.mp4',base).href)).status(),200);
  result.desktop = { ...state, pause:true, playback:true, scrub:true, rotate:true, pan:true, zoom:true, reset:true, presets:true, modelDownload:true, movie:true };
  const mobile = await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true,reducedMotion:'reduce'});
  const phone = await mobile.newPage();phone.on('pageerror',error=>failures.push(error.message));
  await phone.goto(base,{waitUntil:'domcontentloaded'});
  await phone.waitForFunction(()=>window.qingmingViewer?.snapshot().ready,{timeout:120000});
  let phoneState=await phone.evaluate(()=>window.qingmingViewer.snapshot());assert.equal(phoneState.playing,false);
  assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await phone.getByRole('button',{name:'橋上市集',exact:true}).tap();
  const cdp = await mobile.newCDPSession(phone);
  phoneState=await phone.evaluate(()=>window.qingmingViewer.snapshot());
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:170,y:330}]});
  for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:170+i*9,y:330+i*3}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await phone.waitForTimeout(200);
  assert.ok(distance((await phone.evaluate(()=>window.qingmingViewer.snapshot())).camera,phoneState.camera)>1);
  await phone.getByRole('button',{name:'回到初始視角'}).tap();
  await phone.screenshot({path:'test-results/mobile.png'});
  result.mobile={width:390,height:844,noOverflow:true,touchRotate:true,reducedMotionRespected:true};
  assert.deepEqual(failures,[]);
  result.errors=failures;
  fs.writeFileSync('test-results/browser-validation.json',JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
} finally { await browser.close(); }
